-- HWView-EV1 Database Schema Initialization
-- 对应 design.md 第 2.3.2 章，7 张表 DDL
-- 表名规范：TBL_ 前缀加下划线分隔大写格式（PREFERENCE_17）

-- 1. TBL_PRODUCTION_LINE 产线表
CREATE TABLE IF NOT EXISTS TBL_PRODUCTION_LINE (
    id           INTEGER      PRIMARY KEY AUTOINCREMENT,
    line_code    VARCHAR(64)  NOT NULL UNIQUE,
    line_name    VARCHAR(128) NOT NULL,
    customer     VARCHAR(64)  NOT NULL,
    product      VARCHAR(64)  NOT NULL,
    adapter_type VARCHAR(64)  NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    status       VARCHAR(32)  NOT NULL DEFAULT 'UNCONFIGURED',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_PRODUCTION_LINE_CUSTOMER ON TBL_PRODUCTION_LINE(customer);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTION_LINE_PRODUCT  ON TBL_PRODUCTION_LINE(product);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTION_LINE_ENABLED  ON TBL_PRODUCTION_LINE(enabled);

-- EV1 首条真实产线基线
INSERT OR IGNORE INTO TBL_PRODUCTION_LINE (line_code, line_name, customer, product, adapter_type, enabled, status)
VALUES ('HW102-COPY', '华为102复制线', '华为', 'HW102', 'Huawei102Adapter', TRUE, 'UNCONFIGURED');

-- 2. TBL_DATA_SOURCE 数据源表
CREATE TABLE IF NOT EXISTS TBL_DATA_SOURCE (
    id               INTEGER      PRIMARY KEY AUTOINCREMENT,
    line_id          INTEGER      NOT NULL,
    agent_id         VARCHAR(64),
    hostname         VARCHAR(128),
    current_ip       VARCHAR(45)  NOT NULL,
    port             INT          NOT NULL,
    base_path        VARCHAR(256) NOT NULL,
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    status           VARCHAR(32)  NOT NULL DEFAULT 'OFFLINE',
    last_success_at  TIMESTAMP,
    last_error_at    TIMESTAMP,
    last_heartbeat_at TIMESTAMP,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (line_id) REFERENCES TBL_PRODUCTION_LINE(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_DATA_SOURCE_LINE_BASEPATH ON TBL_DATA_SOURCE(line_id, base_path);
CREATE INDEX IF NOT EXISTS IDX_DATA_SOURCE_AGENT   ON TBL_DATA_SOURCE(agent_id);
CREATE INDEX IF NOT EXISTS IDX_DATA_SOURCE_STATUS  ON TBL_DATA_SOURCE(status);
CREATE INDEX IF NOT EXISTS IDX_DATA_SOURCE_ENABLED ON TBL_DATA_SOURCE(enabled);

-- 3. TBL_PRODUCTION_RECORD 生产记录表
CREATE TABLE IF NOT EXISTS TBL_PRODUCTION_RECORD (
    id              INTEGER      PRIMARY KEY AUTOINCREMENT,
    line_id         INTEGER      NOT NULL,
    source_id       VARCHAR(128) NOT NULL,
    product_code    VARCHAR(64)  NOT NULL,
    barcode         VARCHAR(128) NOT NULL,
    batch_no        VARCHAR(64)  NOT NULL,
    quantity        INT          NOT NULL CHECK (quantity >= 0),
    created_at      TIMESTAMP    NOT NULL,
    production_date DATE         NOT NULL,
    collected_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (line_id) REFERENCES TBL_PRODUCTION_LINE(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_RECORD_LINE_SOURCE ON TBL_PRODUCTION_RECORD(line_id, source_id);
CREATE INDEX IF NOT EXISTS IDX_RECORD_LINE_DATE    ON TBL_PRODUCTION_RECORD(line_id, production_date);
CREATE INDEX IF NOT EXISTS IDX_RECORD_DATE         ON TBL_PRODUCTION_RECORD(production_date);
CREATE INDEX IF NOT EXISTS IDX_RECORD_BATCH        ON TBL_PRODUCTION_RECORD(line_id, production_date, batch_no);
CREATE INDEX IF NOT EXISTS IDX_RECORD_CREATED_AT   ON TBL_PRODUCTION_RECORD(line_id, created_at);

-- 4. TBL_COLLECT_CURSOR Cursor 持久化表
CREATE TABLE IF NOT EXISTS TBL_COLLECT_CURSOR (
    id             INTEGER      PRIMARY KEY AUTOINCREMENT,
    line_id        INTEGER      NOT NULL,
    source_id      VARCHAR(128) NOT NULL,
    last_created_at TIMESTAMP   NOT NULL,
    last_source_id VARCHAR(128) NOT NULL,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (line_id) REFERENCES TBL_PRODUCTION_LINE(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS UQ_CURSOR_LINE ON TBL_COLLECT_CURSOR(line_id);

-- 5. TBL_DATA_SOURCE_HEALTH 健康监控表
CREATE TABLE IF NOT EXISTS TBL_DATA_SOURCE_HEALTH (
    source_id            INTEGER      PRIMARY KEY,
    status               VARCHAR(32)  NOT NULL DEFAULT 'OFFLINE',
    last_success_at      TIMESTAMP,
    last_failure_at      TIMESTAMP,
    consecutive_failures INT          NOT NULL DEFAULT 0,
    last_error           TEXT,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (source_id) REFERENCES TBL_DATA_SOURCE(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_HEALTH_STATUS ON TBL_DATA_SOURCE_HEALTH(status);

-- 6. TBL_AGENT Agent 表（EV2 预定义）
CREATE TABLE IF NOT EXISTS TBL_AGENT (
    agent_id         VARCHAR(64)  PRIMARY KEY,
    hostname         VARCHAR(128) NOT NULL,
    machine_id       VARCHAR(128) NOT NULL,
    mac              VARCHAR(32)  NOT NULL,
    ipv4             VARCHAR(45)  NOT NULL,
    last_heartbeat_at TIMESTAMP   NOT NULL,
    bound_line_id    INTEGER,
    status           VARCHAR(32)  NOT NULL DEFAULT 'PENDING_BIND',
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (bound_line_id) REFERENCES TBL_PRODUCTION_LINE(id)
);

CREATE INDEX IF NOT EXISTS IDX_AGENT_MACHINE ON TBL_AGENT(machine_id);
CREATE INDEX IF NOT EXISTS IDX_AGENT_STATUS  ON TBL_AGENT(status);

-- 7. TBL_AUDIT_LOG 审计日志表
CREATE TABLE IF NOT EXISTS TBL_AUDIT_LOG (
    id          INTEGER      PRIMARY KEY AUTOINCREMENT,
    actor       VARCHAR(128) NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    target_type VARCHAR(64)  NOT NULL,
    target_id   VARCHAR(128),
    change      TEXT,
    sudo_used   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_AUDIT_ACTOR ON TBL_AUDIT_LOG(actor);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_TIME  ON TBL_AUDIT_LOG(created_at);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_TARGET ON TBL_AUDIT_LOG(target_type, target_id);